import { sql } from 'drizzle-orm'
import { check, foreignKey, integer, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core'
import { institutions, tenantPolicy, users } from '@campusos/db'

const tenantId = () => uuid('institution_id').notNull().references(() => institutions.id, { onDelete: 'cascade' })
export const vehicles = pgTable('transport_vehicles', { id: uuid().primaryKey().defaultRandom(), institutionId: tenantId(), registration: text().notNull(), capacity: integer().notNull() }, table => [uniqueIndex('transport_vehicle_registration').on(table.institutionId, table.registration), uniqueIndex('transport_vehicles_tenant_id').on(table.institutionId, table.id), check('transport_vehicle_capacity', sql`capacity between 1 and 200`), tenantPolicy('transport_vehicles')])
export const routes = pgTable('transport_routes', { id: uuid().primaryKey().defaultRandom(), institutionId: tenantId(), name: text().notNull(), vehicleId: uuid('vehicle_id').notNull() }, table => [uniqueIndex('transport_route_vehicle').on(table.vehicleId), uniqueIndex('transport_routes_tenant_id').on(table.institutionId, table.id), foreignKey({ columns: [table.institutionId, table.vehicleId], foreignColumns: [vehicles.institutionId, vehicles.id] }), tenantPolicy('transport_routes')])
export const stops = pgTable('transport_stops', { id: uuid().primaryKey().defaultRandom(), institutionId: tenantId(), routeId: uuid('route_id').notNull(), name: text().notNull(), position: integer().notNull() }, table => [uniqueIndex('transport_stop_position').on(table.routeId, table.position), uniqueIndex('transport_stops_route_id').on(table.routeId, table.id), foreignKey({ columns: [table.institutionId, table.routeId], foreignColumns: [routes.institutionId, routes.id] }), check('transport_stop_order', sql`position > 0`), tenantPolicy('transport_stops')])
export const assignments = pgTable('transport_assignments', {
  id: uuid().primaryKey().defaultRandom(), institutionId: tenantId(), routeId: uuid('route_id').notNull(), stopId: uuid('stop_id').notNull(), studentId: text('student_id').notNull().references(() => users.id),
  status: text().notNull().default('active'), releaseReason: text('release_reason'), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), releasedAt: timestamp('released_at', { withTimezone: true }),
}, table => [foreignKey({ columns: [table.institutionId, table.routeId], foreignColumns: [routes.institutionId, routes.id] }), foreignKey({ columns: [table.routeId, table.stopId], foreignColumns: [stops.routeId, stops.id] }), uniqueIndex('transport_student_active').on(table.institutionId, table.studentId).where(sql`status = 'active'`), check('transport_assignment_state', sql`status in ('active','released') and ((status = 'released') = (released_at is not null))`), tenantPolicy('transport_assignments')])
