import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import { plainPaise } from '@campusos/money'

export interface ReceiptData {
  receiptNo: string
  institutionName: string
  studentName: string | null
  studentEmail: string | null
  termCode: string
  termName: string
  amountPaise: number
  method: string
  reference: string | null
  receivedAt: Date
  reconciledAt: Date | null
}

/**
 * A fee receipt. Same toolchain as the transcript, for the same reason: pure
 * JavaScript, so it renders in a serverless function and in CI alike.
 *
 * Amounts are printed with plainPaise, not the locale formatter: a receipt is a
 * document of record, and its figures should not change shape with the server's
 * locale.
 */
const safe = (s: string) => s.replace(/[^\x20-\x7E]/g, '?')

export async function receiptPdf(d: ReceiptData): Promise<Uint8Array> {
  const doc = await PDFDocument.create()
  doc.setTitle(`Receipt ${d.receiptNo}`)
  doc.setProducer('CampusOS')

  // A5 landscape: a receipt, not a report.
  const page = doc.addPage([595.28, 420])
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)

  const ink = rgb(0.1, 0.1, 0.12)
  const faint = rgb(0.45, 0.45, 0.5)
  const M = 40
  let y = 420 - M

  const text = (s: string, x: number, size = 10, f = font, color = ink) =>
    page.drawText(safe(s), { x, y, size, font: f, color })

  text(d.institutionName || 'Institution', M, 15, bold)
  y -= 18
  text('Fee Receipt', M, 10, font, faint)
  text(d.receiptNo, 595.28 - M - font.widthOfTextAtSize(d.receiptNo, 12) - 4, 12, bold)
  y -= 24

  page.drawLine({
    start: { x: M, y: y + 6 },
    end: { x: 595.28 - M, y: y + 6 },
    thickness: 0.5,
    color: rgb(0.8, 0.8, 0.83),
  })
  y -= 18

  const row = (k: string, v: string) => {
    text(k, M, 9, font, faint)
    text(v, M + 150, 10)
    y -= 18
  }

  row('Received from', d.studentName ?? d.studentEmail ?? d.studentEmail ?? '—')
  if (d.studentEmail) row('Email', d.studentEmail)
  row('Term', `${d.termCode} — ${d.termName}`)
  row('Method', d.method.replace(/_/g, ' '))
  if (d.reference) row('Reference', d.reference)
  row('Received on', d.receivedAt.toISOString().slice(0, 10))

  y -= 10
  text('Amount', M, 10, bold)
  const amount = `INR ${plainPaise(d.amountPaise)}`
  text(amount, M + 150, 16, bold)
  y -= 30

  // Stated plainly: an unreconciled payment is a claim, not cleared funds, and
  // a receipt that hides that is the one an institution regrets issuing.
  if (d.reconciledAt) {
    text(
      `Reconciled on ${d.reconciledAt.toISOString().slice(0, 10)}`,
      M,
      9,
      font,
      rgb(0.1, 0.45, 0.2),
    )
  } else {
    text(
      'Pending reconciliation — subject to clearance of funds',
      M,
      9,
      bold,
      rgb(0.6, 0.4, 0),
    )
  }
  y -= 24

  text('Computer generated by CampusOS. No signature required.', M, 7, font, faint)

  return doc.save()
}
